# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18b2706f7b6e9a6515fedd280cb117dcf5dd6d1500e4ea78f2c10abb408b6c06ded7c0d0b4da94fb05c85f42e4dc7db5f72e9628961355e7e32a5628f4327a56

test:
  secret_key_base: a89540904b9561a198dc73cca67573995f778b0d08b360b61b2ccb4f54fe2a351f42c0a224ebf61ab0710e1c1e2cac5562bd433dbf9869f3f71fd832a72b4fc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
